apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:12.0.1
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: KEYCLOAK_IMPORT
              value: /tmp/realm.json
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: localhost:5432
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
          volumeMounts:
            - name: config-volume
              mountPath: /tmp/realm.json
              subPath: realm.json
        - name: postgres
          image: postgres:13.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: keycloak
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: config-volume
          configMap:
            name: keycloak-config
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-pv-claim