spring:
  application.name: users
  profiles.active: oauth
  data:
    mongodb:
      username: mongo
      password: mongo
      database: redditgallery

management:
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true
  endpoint:
    health:
      probes.enabled: true
      show-details: always
  endpoints.web.exposure.include: info,health,refresh

server.port: 8094

reddit-gallery:
  idp:
    host: localhost
    port: 5555
    realm: reddit-gallery
    client-id: reddit-gallery-gateway
    client-secret: 7fa2c40b-9d89-429b-a172-764bdeca0d59
