spring:
  application.name: users
  profiles.active: oauth
  data:
    mongodb:
      username: mongo
      password: mongo
      database: redditgallery

server.port: 8094

reddit-gallery:
  idp:
    host: localhost
    port: 5555
    realm: reddit-gallery
    client-id: reddit-gallery-gateway
    client-secret: 268507bf-e136-4eac-805f-66a99c8eebd1
