spring:
  application.name: gateway
  profiles.active: routes, oauth
  main.banner-mode: off
#  cloud:
#    gateway:
#      httpclient:
#        wiretap: true
#      httpserver:
#        wiretap: true

management:
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true
  endpoint:
    health:
      probes.enabled: true
      show-details: always
  endpoints.web.exposure.include: info,health,refresh

server:
  port: 8093

reddit-gallery:
  idp:
    host: localhost
    port: 5555
    realm: reddit-gallery
    client-id: reddit-gallery
    client-secret: d9e8eb84-5062-4abd-b974-f3df79054e4e

#logging.level:
#  reactor.netty: DEBUG
#  org.springframework.web: DEBUG
#  org.springframework.cloud.gateway: TRACE
#  org.springframework.security: DEBUG
#  org.springframework.web.reactive.function.client: TRACE