spring:
  application.name: gateway
  profiles.active: routes, oauth
  main.banner-mode: off
#  cloud:
#    gateway:
#      httpclient:
#        wiretap: true
#      httpserver:
#        wiretap: true

server:
  port: 8093

reddit-gallery:
  idp:
    realm: reddit-gallery
    client-id: reddit-gallery
    client-secret: 7b335bc6-c9e4-47e9-a4f9-9899ae7037f0

#logging.level:
#  reactor.netty: DEBUG
#  org.springframework.web: DEBUG
#  org.springframework.cloud.gateway: TRACE
#  org.springframework.security: DEBUG
#  org.springframework.web.reactive.function.client: TRACE