apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      name: http
  type: ClusterIP
  selector:
    app: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  ports:
    - port: 8081
      name: http
  type: ClusterIP
  selector:
    app: mongo