apiVersion: v1
data:
  MONGO_INITDB_DATABASE: redditgallery
  MONGO_INITDB_PASSWORD: mongo
  MONGO_INITDB_ROOT_PASSWORD: mongo
  MONGO_INITDB_ROOT_USERNAME: mongo
  MONGO_INITDB_USERNAME: mongo
  MONGO_REPLICA_SET_NAME: rs0
  MONGO_URL: mongodb://mongodb:27017
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mongo-env
