apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8.9-management-alpine
          ports:
            - containerPort: 15672
            - containerPort: 5672
          envFrom:
            - configMapRef:
                name: rabbitmq-env