apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - port: 5672
      name: queue
  type: ClusterIP
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
spec:
  ports:
    - port: 15672
      name: http
  type: ClusterIP
  selector:
    app: rabbitmq