version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.1
    ports:
      - "5555:8080"
      - "15555:9990"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm.json
      DB_VENDOR: postgres
      DB_ADDR: postgres:5432
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      -  ./keycloak/realm.json:/tmp/realm.json
  postgres:
    image: postgres:13.1
    ports:
      - "5432:5432"
    volumes:
      - ~/dev/mount/postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: keycloak
      PGDATA: /var/lib/postgresql/data/pgdata
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/dev/mount/rabbitmq_data:/var/lib/rabbitmq
    hostname: rabbitmq-host
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
  mongo:
    image: mongo:3
    hostname: mongodb
    restart: always
    volumes:
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/initdb.d/:/docker-entrypoint-initdb.d/
      - ~/dev/mount/mongodb_data:/data/db/
    env_file:
      - ./mongo/.env
    ports:
      - "27017:27017"
    command: ["-f", "/etc/mongod.conf"]
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
  minio:
    image: minio/minio:RELEASE.2021-01-08T21-18-21Z
    ports:
      - "9000:9000"
    volumes:
      - ~/dev/mount/minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
    command:
      - server
      - /data
